require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Core::PermissionsController do

  # This should return the minimal set of attributes required to create a valid
  # Core::Permission. As you add validations to Core::Permission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "module_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Core::PermissionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all core_permissions as @core_permissions" do
      permission = Core::Permission.create! valid_attributes
      get :index, {}, valid_session
      assigns(:core_permissions).should eq([permission])
    end
  end

  describe "GET show" do
    it "assigns the requested core_permission as @core_permission" do
      permission = Core::Permission.create! valid_attributes
      get :show, {:id => permission.to_param}, valid_session
      assigns(:core_permission).should eq(permission)
    end
  end

  describe "GET new" do
    it "assigns a new core_permission as @core_permission" do
      get :new, {}, valid_session
      assigns(:core_permission).should be_a_new(Core::Permission)
    end
  end

  describe "GET edit" do
    it "assigns the requested core_permission as @core_permission" do
      permission = Core::Permission.create! valid_attributes
      get :edit, {:id => permission.to_param}, valid_session
      assigns(:core_permission).should eq(permission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Core::Permission" do
        expect {
          post :create, {:core_permission => valid_attributes}, valid_session
        }.to change(Core::Permission, :count).by(1)
      end

      it "assigns a newly created core_permission as @core_permission" do
        post :create, {:core_permission => valid_attributes}, valid_session
        assigns(:core_permission).should be_a(Core::Permission)
        assigns(:core_permission).should be_persisted
      end

      it "redirects to the created core_permission" do
        post :create, {:core_permission => valid_attributes}, valid_session
        response.should redirect_to(Core::Permission.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved core_permission as @core_permission" do
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Permission.any_instance.stub(:save).and_return(false)
        post :create, {:core_permission => { "module_name" => "invalid value" }}, valid_session
        assigns(:core_permission).should be_a_new(Core::Permission)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Permission.any_instance.stub(:save).and_return(false)
        post :create, {:core_permission => { "module_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested core_permission" do
        permission = Core::Permission.create! valid_attributes
        # Assuming there are no other core_permissions in the database, this
        # specifies that the Core::Permission created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Core::Permission.any_instance.should_receive(:update).with({ "module_name" => "MyString" })
        put :update, {:id => permission.to_param, :core_permission => { "module_name" => "MyString" }}, valid_session
      end

      it "assigns the requested core_permission as @core_permission" do
        permission = Core::Permission.create! valid_attributes
        put :update, {:id => permission.to_param, :core_permission => valid_attributes}, valid_session
        assigns(:core_permission).should eq(permission)
      end

      it "redirects to the core_permission" do
        permission = Core::Permission.create! valid_attributes
        put :update, {:id => permission.to_param, :core_permission => valid_attributes}, valid_session
        response.should redirect_to(permission)
      end
    end

    describe "with invalid params" do
      it "assigns the core_permission as @core_permission" do
        permission = Core::Permission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Permission.any_instance.stub(:save).and_return(false)
        put :update, {:id => permission.to_param, :core_permission => { "module_name" => "invalid value" }}, valid_session
        assigns(:core_permission).should eq(permission)
      end

      it "re-renders the 'edit' template" do
        permission = Core::Permission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Permission.any_instance.stub(:save).and_return(false)
        put :update, {:id => permission.to_param, :core_permission => { "module_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested core_permission" do
      permission = Core::Permission.create! valid_attributes
      expect {
        delete :destroy, {:id => permission.to_param}, valid_session
      }.to change(Core::Permission, :count).by(-1)
    end

    it "redirects to the core_permissions list" do
      permission = Core::Permission.create! valid_attributes
      delete :destroy, {:id => permission.to_param}, valid_session
      response.should redirect_to(core_permissions_url)
    end
  end

end
